/-
Copyright (c) 2026 Zichen Wang, Wanli Ma. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zichen Wang, Wanli Ma
-/
import MatDecompFormal.Instances.OrthogonalHessenberg.Strategy

universe u

namespace MatDecompFormal.Instances

open Matrix
open MatDecompFormal.Framework

/-!
# Orthogonal/Unitary Hessenberg Direct Hooks

This file assembles the proof-side hooks for the boundary-column subtype
descent.  The oracle is unitary; the recursive structure is the same boundary
universe used by ordinary Hessenberg reduction.
-/

/-- Unitarly transformed positive boundary object. -/
noncomputable def unitaryHessenbergBoundaryStepObject
    (oracle : UnitaryHessenbergBoundaryStepOracle.{u})
    (x_sub : PosHessenbergBoundaryUniverse ℂ) :
    PosHessenbergBoundaryUniverse ℂ :=
  ⟨unitaryHessenbergBoundarySimilarityObject
      (x_sub : HessenbergBoundaryUniverse.{u} ℂ) (oracle.Q x_sub),
    by simpa [unitaryHessenbergBoundarySimilarityObject] using x_sub.2⟩

/-- Relation generated by one oracle-provided unitary similarity step. -/
def unitaryHessenbergBoundaryStepRel
    (oracle : UnitaryHessenbergBoundaryStepOracle.{u})
    (y_sub x_sub : PosHessenbergBoundaryUniverse ℂ) : Prop :=
  y_sub = unitaryHessenbergBoundaryStepObject oracle x_sub

/--
Boundary target transport across a same-index unitary similarity.
-/
theorem unitaryHessenbergBoundary_transport_unitarySimilarity
    (x : HessenbergBoundaryUniverse.{u} ℂ)
    (Q : Matrix x.ι x.ι ℂ)
    (hQ : IsUnitaryMatrix Q)
    (hY :
      UnitaryHessenbergBoundary_P
        (unitaryHessenbergBoundarySimilarityObject x Q)) :
    UnitaryHessenbergBoundary_P x := by
  intro hxNonempty
  have hY' :
      HasUnitaryHessenbergBoundary (Qᴴ * x.A * Q) (Qᴴ * x.c) := by
    simpa [unitaryHessenbergBoundarySimilarityObject] using hY hxNonempty
  rcases hY' with ⟨S, H, hS, hH, hEqY, hBoundaryY⟩
  refine ⟨Q * S, H, isUnitaryMatrix_mul hQ hS, hH, ?_, ?_⟩
  · calc
      x.A = (Q * Qᴴ) * x.A * (Q * Qᴴ) := by
        simp [hQ.2]
      _ = Q * (Qᴴ * x.A * Q) * Qᴴ := by
        simp [Matrix.mul_assoc]
      _ = Q * (S * H * Sᴴ) * Qᴴ := by
        rw [hEqY]
      _ = (Q * S) * H * (Q * S)ᴴ := by
        rw [Matrix.conjTranspose_mul]
        simp [Matrix.mul_assoc]
  · intro i hi
    have hboundary := hBoundaryY i hi
    simpa [Matrix.conjTranspose_mul, Matrix.mul_assoc] using hboundary

/-- Block-diagonal tail unitary lift for the boundary target. -/
theorem hasUnitaryHessenbergBoundary_fromBlocks_of_tail
    {β : Type*} [Fintype β] [DecidableEq β] [LinearOrder β] [Nonempty β]
    (A₁₁ : Matrix Unit Unit ℂ) (A₁₂ : Matrix Unit β ℂ)
    (A₂₁ : Matrix β Unit ℂ) (A₂₂ : Matrix β β ℂ)
    (c : Matrix (Unit ⊕ₗ β) Unit ℂ)
    (hc : ∀ i : β, c (Sum.inrₗ i) () = 0)
    (hTail : HasUnitaryHessenbergBoundary A₂₂ A₂₁) :
    HasUnitaryHessenbergBoundary (ι := Unit ⊕ₗ β)
      (fromBlocks A₁₁ A₁₂ A₂₁ A₂₂ : Matrix (Unit ⊕ₗ β) (Unit ⊕ₗ β) ℂ)
      c := by
  rcases hTail with ⟨Qtail, Htail, hQtail, hHTail, hEqTail, hBoundaryTail⟩
  let Qblk : Matrix (Unit ⊕ₗ β) (Unit ⊕ₗ β) ℂ := hessenbergBlockDiagOne Qtail
  let Hblk : Matrix (Unit ⊕ₗ β) (Unit ⊕ₗ β) ℂ :=
    fromBlocks A₁₁ (A₁₂ * Qtail) (Qtailᴴ * A₂₁) Htail
  have hInvTail : HasMatrixInverse Qtail Qtailᴴ :=
    hasMatrixInverse_of_isUnitaryMatrix hQtail
  have hQblk_conj :
      Qblkᴴ = hessenbergBlockDiagOne Qtailᴴ := by
    change (hessenbergBlockDiagOne Qtail)ᴴ = hessenbergBlockDiagOne Qtailᴴ
    rw [hessenbergBlockDiagOne, hessenbergBlockDiagOne]
    rw [Matrix.fromBlocks_conjTranspose]
    simp
  refine ⟨Qblk, Hblk, ?_, ?_, ?_, ?_⟩
  · exact isUnitaryMatrix_blockDiag_one hQtail
  · exact
      isUpperHessenberg_fromBlocks_ready
        A₁₁ (A₁₂ * Qtail) (Qtailᴴ * A₂₁) Htail hBoundaryTail hHTail
  · rw [hQblk_conj]
    simpa [Qblk, Hblk] using
      hessenbergBlockDiagOne_parentBlock_eq
        A₁₁ A₁₂ A₂₁ A₂₂ Htail Qtail Qtailᴴ hInvTail hEqTail
  · intro i hi
    cases h : ofLex i with
    | inl u =>
        cases u
        have hi_eq : i = (Sum.inlₗ () : Unit ⊕ₗ β) := by
          rw [← toLex_ofLex i, h]
        exact False.elim (hi (by simpa [headElem_sumLex_unit] using hi_eq))
    | inr j =>
        have hi_eq : i = (Sum.inrₗ j : Unit ⊕ₗ β) := by
          rw [← toLex_ofLex i, h]
        subst i
        have htail :=
          hessenbergBlockDiagOne_mul_readyColumn_tail Qtailᴴ c hc j
        rw [hQblk_conj]
        exact htail

/-- Lift from a ready boundary object and its recursive unitary tail witness. -/
theorem unitaryHessenbergBoundary_lift_from_ready
    (x_sub : PosHessenbergBoundaryUniverse.{u} ℂ)
    (hReady : HessenbergBoundaryReady (x_sub : HessenbergBoundaryUniverse.{u} ℂ))
    (hTail : UnitaryHessenbergBoundary_P (hessenbergBoundarySliceSub x_sub)) :
    UnitaryHessenbergBoundary_P (x_sub : HessenbergBoundaryUniverse.{u} ℂ) := by
  intro hxNonempty
  letI : Nonempty x_sub.1.ι := hxNonempty
  let β := HessenbergTailIdx x_sub.1.ι
  let Aplain : Matrix (Unit ⊕ β) (Unit ⊕ β) ℂ :=
    hessenbergBoundaryHeadTailMatrix x_sub.1.ι x_sub.1.A
  let cblk : Matrix (Unit ⊕ₗ β) Unit ℂ :=
    Matrix.reindex (headTailLexEquiv (α := x_sub.1.ι)) (Equiv.refl Unit) x_sub.1.c
  by_cases hβ : Nonempty β
  · letI : Nonempty β := hβ
    have hTailBoundary :
        HasUnitaryHessenbergBoundary Aplain.toBlocks₂₂ Aplain.toBlocks₂₁ := by
      have hP := hTail hβ
      simpa [hessenbergBoundarySliceSub, hessenbergTailSlice_eq_boundaryLowerRightBlock,
        hessenbergBoundaryLowerLeftColumn, Aplain] using hP
    have hcblk : ∀ i : β, cblk (Sum.inrₗ i) () = 0 := by
      intro i
      simpa [cblk, headTailLexEquiv_symm_apply_inr] using
        hReady hxNonempty i i.2
    have hBlock : HasUnitaryHessenbergBoundary (ι := Unit ⊕ₗ β)
        (fromBlocks Aplain.toBlocks₁₁ Aplain.toBlocks₁₂ Aplain.toBlocks₂₁ Aplain.toBlocks₂₂ :
          Matrix (Unit ⊕ₗ β) (Unit ⊕ₗ β) ℂ)
        cblk :=
      hasUnitaryHessenbergBoundary_fromBlocks_of_tail Aplain.toBlocks₁₁ Aplain.toBlocks₁₂
        Aplain.toBlocks₂₁ Aplain.toBlocks₂₂ cblk hcblk hTailBoundary
    have hLexEq :
        Matrix.reindex (headTailLexEquiv (α := x_sub.1.ι))
          (headTailLexEquiv (α := x_sub.1.ι)) x_sub.1.A =
        (fromBlocks Aplain.toBlocks₁₁ Aplain.toBlocks₁₂ Aplain.toBlocks₂₁ Aplain.toBlocks₂₂ :
          Matrix (Unit ⊕ₗ β) (Unit ⊕ₗ β) ℂ) := by
      simpa [Aplain, β] using hessenbergBoundaryHeadTailLex_fromBlocks x_sub.1.ι x_sub.1.A
    have hLex : HasUnitaryHessenbergBoundary
        (Matrix.reindex (headTailLexEquiv (α := x_sub.1.ι))
          (headTailLexEquiv (α := x_sub.1.ι)) x_sub.1.A)
        cblk := by
      rw [hLexEq]
      exact hBlock
    rcases hLex with ⟨Q, H, hQ, hH, hEq, hBoundary⟩
    let e := headTailLexEquiv (α := x_sub.1.ι)
    let Q0 : Matrix x_sub.1.ι x_sub.1.ι ℂ := Matrix.reindex e.symm e.symm Q
    let H0 : Matrix x_sub.1.ι x_sub.1.ι ℂ := Matrix.reindex e.symm e.symm H
    refine ⟨Q0, H0, ?_, ?_, ?_, ?_⟩
    · exact isUnitaryMatrix_reindex e.symm hQ
    · exact
        (isUpperHessenberg_reindex_strictMono
          (e := e.symm)
          (h_mono := by
            intro x y hxy
            have hxy' : e (e.symm x) < e (e.symm y) := by
              simpa using hxy
            exact (headTailLexEquiv_strictMono (α := x_sub.1.ι)).lt_iff_lt.mp hxy')
          (A := H)).2 hH
    · have hback := congrArg (Matrix.reindex e.symm e.symm) hEq
      simpa [Q0, H0, e, Matrix.conjTranspose_reindex, Matrix.submatrix_mul_equiv,
        Matrix.mul_assoc] using hback
    · intro i hi
      have hb : (Qᴴ * cblk) (e i) () = 0 := by
        apply hBoundary
        intro heq
        apply hi
        have hhead := headElem_map_strictMono e
          (headTailLexEquiv_strictMono (α := x_sub.1.ι))
        exact e.injective (by simpa [hhead] using heq)
      have hmul := reindex_mul_column e Qᴴ x_sub.1.c
      have hb_re := congrFun (congrFun hmul i) ()
      have hb0 : ((Matrix.reindex e.symm e.symm Qᴴ) * x_sub.1.c) i () = 0 := by
        rw [← hb_re]
        exact hb
      simpa [Q0, Matrix.conjTranspose_reindex] using hb0
  · have hsub : Subsingleton x_sub.1.ι := by
      refine ⟨?_⟩
      intro a b
      by_cases ha : a = headElem (α := x_sub.1.ι)
      · by_cases hb : b = headElem (α := x_sub.1.ι)
        · rw [ha, hb]
        · have : Nonempty β := ⟨⟨b, hb⟩⟩
          exact False.elim (hβ this)
      · have : Nonempty β := ⟨⟨a, ha⟩⟩
        exact False.elim (hβ this)
    letI : Subsingleton x_sub.1.ι := hsub
    refine ⟨1, x_sub.1.A, isUnitaryMatrix_one, ?_, ?_, ?_⟩
    · exact isUpperHessenberg_subsingleton x_sub.1.A
    · simp
    · intro i hi
      exact False.elim (hi (Subsingleton.elim _ _))

end MatDecompFormal.Instances
